### ISSUE TITLE
Praca domowa - wykład 3 - struktura artykułu

### ISSUE THREAD

**Issue by woznicak** [mini-pw/2021L-WarsztatyBadawcze#2]
- Zlokalizujcie w tekście sekcje wprowadzenia, metod, rezultatów i dyskusji. Czy są ułożone standardowo? Jeśli nie to zastanówcie się czemu miał służyć taki zabieg.
- Czy sekcje są podzielone na mniejsze podsekcje? Jak skonstruowane są podtytuły?
- Przy pomocy jakich środków zostały pokazane rezultaty? Jak opisane są wykresy i tabele? 

Do dyskusji wybierzcie artykuł, który Was czymś zaskoczył (na minus albo na plus) w strukturze.

Przykładowe źródła artykułów:
- [arvix - machine learning](https://arxiv.org/list/cs.LG/new)
- [arvix - computer vision](https://arxiv.org/list/cs.CV/new)
- [Journal of Machine Leaning](https://www.jmlr.org/)
- [KDD 2020](https://www.kdd.org/kdd2020/proceedings/)

**Comment by jaszczukp** [comment]
[WB_analiza_artykułu.pdf](https://github.com/mini-pw/2021L-WarsztatyBadawcze/files/6163858/WB_analiza_artykulu.pdf)

**Comment by SawickiBartosz** [comment]
[Deep-learnin-based-extreme-heatwave-forecast.pdf](https://github.com/mini-pw/2021L-WarsztatyBadawcze/files/6167471/Deep-learnin-based-extreme-heatwave-forecast.pdf)

**Comment by karik16** [comment]
[Asymptotic behavior of Support Vector Machine.pdf](https://github.com/mini-pw/2021L-WarsztatyBadawcze/files/6169700/Asymptotic.behavior.of.Support.Vector.Machine.pdf)
[Topology of Deep Neural Networks.pdf](https://github.com/mini-pw/2021L-WarsztatyBadawcze/files/6169704/Topology.of.Deep.Neural.Networks.pdf)

**Comment by MattS0000** [comment]
[WB1_Wykład3_pd.pdf](https://github.com/mini-pw/2021L-WarsztatyBadawcze/files/6169910/WB1_Wyklad3_pd.pdf)
