### ISSUE TITLE
Praca domowa - wykład 3 - aspekty językowe

### ISSUE THREAD

**Issue by woznicak** [mini-pw/2021L-WarsztatyBadawcze#3]
- zaznaczcie po dwa cytowania skupione na informacjach, autorze i mieszane
- jaki czas został zastosowany we wprowadzeniu Present Simple czy Present Perfect?
- W sekcji metody i rezultaty dominuje strona bierna czy czynna? Znajdźcie przykłady zastosowania strony biernej i czynnej

**Comment by jaszczukp** [comment]
[WB_analiza_artykułu.pdf](https://github.com/mini-pw/2021L-WarsztatyBadawcze/files/6163865/WB_analiza_artykulu.pdf)

**Comment by SawickiBartosz** [comment]
[Deep-learnin-based-extreme-heatwave-forecast.pdf](https://github.com/mini-pw/2021L-WarsztatyBadawcze/files/6167473/Deep-learnin-based-extreme-heatwave-forecast.pdf)

**Comment by karik16** [comment]
[Asymptotic behavior of Support Vector Machine.pdf](https://github.com/mini-pw/2021L-WarsztatyBadawcze/files/6169696/Asymptotic.behavior.of.Support.Vector.Machine.pdf)
[Topology of Deep Neural Networks.pdf](https://github.com/mini-pw/2021L-WarsztatyBadawcze/files/6169698/Topology.of.Deep.Neural.Networks.pdf)

**Comment by MattS0000** [comment]
[WB1_Wykład3_pd.pdf](https://github.com/mini-pw/2021L-WarsztatyBadawcze/files/6169914/WB1_Wyklad3_pd.pdf)
