### ISSUE TITLE
Praca domowa - wykład 4 - bibliografia

### ISSUE THREAD

**Issue by woznicak** [mini-pw/2021L-WarsztatyBadawcze#4]
W temacie Waszych projektów znajdźcie artykuły, które warto będzie zacytować we wprowadzeniu w Waszym artykule (mogą to być prace, które reprodukujecie lub prace, w których zostały opublikowane metody, które wykorzystujecie).

Dla wybranych czasopism stwórzcie plik .bib.

**Comment by MattS0000** [comment]
[bibliography.zip](https://github.com/mini-pw/2021L-WarsztatyBadawcze/files/6210219/bibliography.zip)

**Comment by SawickiBartosz** [comment]
[bibliografia.zip](https://github.com/mini-pw/2021L-WarsztatyBadawcze/files/6210223/bibliografia.zip)

**Comment by karik16** [comment]
[bibliografia.zip](https://github.com/mini-pw/2021L-WarsztatyBadawcze/files/6210422/bibliografia.zip)
