### ISSUE TITLE
Praca domowa - wykład 4 - aspekty językowe

### ISSUE THREAD

**Issue by woznicak** [mini-pw/2021L-WarsztatyBadawcze#5]
Przeanalizujcie fragmenty artykułów i zobaczcie
- jaka jest odległość pomiędzy podmiotem i orzeczeniem (możecie obliczyć średnią dla akapitu)
- jak wprowadzone czy często i jak używane są transition terms

**Comment by karik16** [comment]
[Benchmarking deep learning models.pdf](https://github.com/mini-pw/2021L-WarsztatyBadawcze/files/6210429/Benchmarking.deep.learning.models.pdf)

**Comment by MattS0000** [comment]
[RMDL.pdf](https://github.com/mini-pw/2021L-WarsztatyBadawcze/files/6210474/RMDL.pdf)
